### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by jj15warrior** [firstapostle/Blood#4]
this is a malicious or semi-malicious program. reverse engineering in progress

**Comment by firstapostle** [comment]
You mean donttuch.exe ? Forgot to delete it from the git. Drunkenly put it in there.

**Comment by firstapostle** [comment]
Already deleted. Thanks for reminding me.

**Comment by flage** [comment]
Would not trust this. Some nasty code might be hidden in due obfuscation+base64+eval:
`blood.py` file.

**Comment by firstapostle** [comment]
This is an attempt to protect your project from schoolboys who claim to develop "brand new" scripts by changing the name of existing ones

**Comment by firstapostle** [comment]
Is this a stupid joke? Deobfuscating base64 can be done in 2 seconds. :)

**Comment by flage** [comment]
I this your excuse now? Last time you were drunk and uploaded wrong .exe file now you obfuscate for code protection. Doesn't even sound legit an legit excuse when you leave whole linux python script in non-obfuscated....
Btw thanks for @HempWeed #6 for looking into this code, since I had no time inspect it during my *schoolboy* work hours.
